spring.application.name=nexus-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/nexusdb
spring.datasource.username=postgres
spring.datasource.password=nexus123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379

minio.endpoint=http://localhost:9000
minio.access-key=nexusadmin
minio.secret-key=nexus123
minio.bucket-name=nexus-resumes

jwt.secret=nexus-super-secret-key-for-jwt-signing-minimum-32chars
jwt.expiration-ms=86400000

groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile
assemblyai.api.key=da81187e7b7342c3ba8785bccf73cbdf

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Email Configuration
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saibachhav04@gmail.com
spring.mail.password=kmvfzkvwoxumozho
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.frontend.url=http://localhost:3000