# Database ? Railway provides this automatically
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis ? Railway provides this
spring.data.redis.url=${REDIS_URL}

# MinIO
minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=nexus-resumes

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# Groq AI
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# AssemblyAI
assemblyai.api.key=${ASSEMBLYAI_KEY}

# Frontend URL
app.frontend.url=${FRONTEND_URL}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Port
server.port=${PORT:8080}